### ISSUE TITLE
Serve RSS/Atom in https://www.holaxprogramming.com/

### ISSUE THREAD

**Issue by onacit** [stunstunstun/awesome-algorithms#3]
안녕하세요. 어디다가 연락들 드려야 할 지 몰라서....

RSS/Atom 가능할까요? 구독하고 싶어서요...

감사합니다.

**Comment by stunstunstun** [comment]
안녕하세요 :)

말씀하신 블로그의 피드라면 주소가 있습니다. 
- https://www.holaxprogramming.com/atom.xml

고맙습니다!

**Comment by onacit** [comment]
Thanks.
